apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: jenkins
  labels:
    name: jenkins
spec:
  serviceName: "jenkins"        
  replicas: 1
  template: 
    metadata:
      name: jenkins        
      labels:
        name: jenkins
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
        runAsUser: 0          
      containers:
      - name: jenkins
        image: jenkinsci/jenkins
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        ports:
        - containerPort: 8080 
          name: web
        - containerPort: 50000
          name: agent
        livenessProbe: 
          httpGet: 
            path: /login
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12 # ~2 minutes
        readinessProbe: 
          httpGet: 
            path: /login
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12 # ~2 minutes          
      volumes:
      - name: jenkins-home
        persistentVolumeClaim: 
          claimName: pvc-jenkins 
